# local/prod
env: local

servicePorts:
  react: 80
  log: 3099

serviceType:
  react: ClusterIP
  log: ClusterIP

containerPorts:
  react: 3030
  log: 3099

replicas:
  react: 1
  log: 1

containerImage:
  react: gauti019/kube-deploy
  log: gauti019/logger-microservice

commitId: 7c22b91e8ffd08f80a8fc6288e92f1e068281d80
