# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions


name: Logger Microservice Pipeline

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: "mcr.microsoft.com/dotnet/core/aspnet:3.1"
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2

      - name: "Use Node.js 10.x"
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Build and push to docker hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          repository: gauti019/logger-microservice
          tags: latest
